ad = input("adınızı giriniz :")
soyad = input("soyadınzı giriniz :")
yas = input("yaşınızı giriniz :")
dogumyeri = input("doğum yerinizi  giriniz :")
kardesayisi = input("kardeş sayınızı giriniz :")
anaadı = input("anne adınızı giriniz :")
babaadi = input("baba adınızı giriniz giriniz :")
ders = input("en sevdiğiniz dersi giriniz :")
oyun = input("en sevdiğiniz oyunu giriniz :")
yemek = input("en sevdiğiniz yemeği giriniz :")


print("adı:",ad)
print("soyadı:",soyad)
print("yaşınızı:",yas)
print("doğum yeri:",dogumyeri)
print("anne adı:",anaadı)
print("baba adı:",babaadi)
print("kardeş sayısı:",kardesayisi)
print("adı:",ders)
print("adı:",oyun)
print("adı:",yemek)
